[package]
name = "ce"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
aws-config = { version = "1.8.14", features = ["behavior-version-latest"] }
aws-sdk-costexplorer = "1.111.0"
chrono = "0.4.44"
anyhow = "1.0.102"
